#ifndef RVISS_ISA_OPCODE_H
#define RVISS_ISA_OPCODE_H

enum class Opcode {
    LUI, AUIPC, ADDI, SLTI, SLTIU, XORI,
    ORI, ANDI, SLLI, SRLI, SRAI, ADD,
    SUB, SLL, SLT, SLTU, XOR, SRL, SRA,
    OR, AND, FENCE, FENCE_I, CSRRW, CSRRS,
    CSRRC, CSRRWI, CSRRSI, CSRRCI, ECALL,
    EBREAK, URET, SRET, MRET, WFI, SFENCE_VMA,
    LB, LH, LW, LBU, LHU, SB, SH, JAL, JALR, BEQ,
    BNE, BLT, BGE, BLTU, BGEU, ADDIW, SLLIW, SRLIW,
    LR_W, SC_W, AMOSWAP_W, AMOADD_W, AMOXOR_W,
    AMOAND_W, AMOOR_W, AMOMIN_W, AMOMAX_W, AMOMINU_W,
    AMOMAXU_W, LR_D, SC_D, AMOSWAP_D, AMOADD_D, AMOXOR_D,
    AMOAND_D, AMOOR_D, AMOMIN_D, AMOMAX_D, AMOMINU_D,
    AMOMAXU_D,
    SRAIW, MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM,
    REMU, MULW, DIVW, DIVUW, REMW, REMUW, ADDW,
    SUBW, SLLW, SRLW, SRAW, LWU,
    LD, SD
};

#endif
