#ifndef RVISS_ISA_OPCODE_H
#define RVISS_ISA_OPCODE_H

enum class Opcode {
    LUI, AUIPC, ADDI, SLTI, SLTIU, XORI,
    ORI, ANDI, SLLI, SRLI, SRAI, ADD,
    SUB, SLL, SLT, SLTU, XOR, SRL, SRA,
    OR, AND, FENCE, FENCE_I, CSRRW, CSRRS,
    CSRRC, CSRRWI, CSRRSI, CSRRCI, ECALL,
    EBREAK, URET, SRET, MRET, WFI, SFENCE_VMA,
    LB, LH, LW, LBU, LHU, SB, SH, JAL, JALR, BEQ,
    BNE, BLT, BGE, BLTU, BGEU, ADDIW, SLLIW, SRLIW,
    SRAIW, MUL, MULH, MULHSU, MULHU, DIV, DIVU, REM,
    REMU, ADDW, SUBW, SLLW, SRLW, SRAW, LWU,
    LD, SD
};

#endif
